<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 */
return array (
  'running' => 'Running',
  'blocked' => 'Blocked',
  'paused' => 'Paused',
  'shutdown' => 'Shutdown',
  'stopped' => 'Stopped',
  'crashed' => 'Crashed',
  'suspended' => 'Suspended',
  'golden' => 'Golden',
  'golden_active' => 'Golden aktiv',
  'active' => 'aktiv',
  'sys-prep' => 'Sys-Prep',
  'free' => 'Frei',
  'backing up' => 'sichert',
  'migrating' => 'migriert',
  'streaming' => 'streaming',
  'preparing' => 'preparing',
);
